### PR TITLE
bugsnag: Bump to latest v1

### PR DESCRIPTION
**Pull request by mheffner**
While there is a v2 API, at the moment logrus_bugsnag doesn't support v2.

### CODE REVIEW

**Comment by rybit** [comment]
I was looking for any uses of that feature in our in our org, I can't find any reference to it. What do you think about deleting it? We are about to do

**Review by rybit — APPROVED** [review]

**Comment by mheffner** [comment]
> I was looking for any uses of that feature in our in our org, I can't find any reference to it. What do you think about deleting it? We are about to do

You're referring to the `LogHook` portion?

**Comment by rybit** [comment]
yeah that is what I was [searching for](https://cs.github.com/?scopeName=netlify&scope=org%3Anetlify&q=log_hook%20org%3Anetlify) it would be specified in the config files.

**Comment by mheffner** [comment]
yeah, looks like @mraerino has a parallel PR in #281 so happy to close this one

**Comment by mraerino** [comment]
sorry didn't see this was open

**Pull request closed without merging**
