### PR TITLE
Bugsnag updates

### PR DESCRIPTION
**Pull request by mheffner**
Looking to test this out on eventeer, so reviving the original implementation here. Two updates:

1. Passed the current app version to BugSnag config in order to track releases in the app.
2. Updates to the latest golang release.

### CODE REVIEW

**Comment by rybit** [comment]
the changes look good - I'd try playing with it in eventeer without merging and see if it adds value. I'm not sure that it being in the hook will work well

**Comment by mheffner** [comment]
> the changes look good - I'd try playing with it in eventeer without merging and see if it adds value. I'm not sure that it being in the hook will work well

Sounds good, I'll give that a shot. We could also make the hook behavior opt-in with a config option I guess.

**Comment by rybit** [comment]
At the time of writing the component I was of the mindset “configure it and it is on” now I am more of the “explicit config option” mindset. 

Lmk if this work well.

**Comment by mheffner** [comment]
Testing this out in https://github.com/netlify/eventeer/pull/31

I updated this PR to pull Bugsnag configuration out of the logging configuration and make the log hook integration optional. Since we are making it optional, it didn't seem appropriate to configure it with the logging config.

**Comment by mraerino** [comment]
Would this mean that every service that is using bugsnag now would need to change their config structure when upgrading netlify-commons?

**Comment by mheffner** [comment]
> Would this mean that every service that is using bugsnag now would need to change their config structure when upgrading netlify-commons?

It would yes, do you have an idea of how many services are using Bugsnag right now?

**Comment by rybit** [comment]
to my knowledge - 0 go services use bugsnag atm

**Comment by mheffner** [comment]
@rybit You ok with this change? Seems to work in eventeer so far, though log hook is still opt-in.

**Comment by rybit** [comment]
yeah I'm cool with breaking it out

**Pull request merged**
