### PR TITLE
Add SafeDial to block connections

### LINKED ISSUE #255: `SafeRoundTripper` can leak goroutines
A context is created [here](https://github.com/netlify/netlify-commons/blob/master/http/http.go#L52) but the cancel function doesn't get called unless there's an error.

### PR DESCRIPTION
**Pull request by mrdg**
Closes #255

### CODE REVIEW

**Review by mraerino — COMMENTED** [review]
could we instead alter `SafeRoundtripper` and `SafeHTTPClient` to use the SafeDial function? this would allow continued use and is probably a good abstraction right?

**Comment by mrdg** [comment]
> could we instead alter `SafeRoundtripper` and `SafeHTTPClient` to use the SafeDial function? this would allow continued use and is probably a good abstraction right?

`SafeRoundtripper` takes an `http.RoundTripper` so you can't configure the dial function on that like with `http.Transport`

**Comment by mraerino** [comment]
maybe offer a safe transport abstraction?

**Comment by mrdg** [comment]
> maybe offer a safe transport abstraction?

Added `SafeTransport`. I kept `SafeDial` exported in case callers need to set custom dialer settings.

**Review by mraerino — APPROVED** [review]
nice!

**Pull request merged**
