### PR TITLE
github tools: fix fossa workflow file

### PR DESCRIPTION
**Pull request by tools-netlify**
Updates github actions fossa workflow to use environment files instead of deprecated set-env command.

### CODE REVIEW

**Comment by tools-netlify** [comment]
don't merge this in yet, this requires custom updates

**Comment by mraerino** [comment]
@emilyzhang should we try to get this merged?

**Comment by keiko713** [comment]
I think we want to merge this (as I don't like seeing ❌ ), will rebase and see how it goes

**Review by keiko713 — APPROVED** [review]
Uhmm, manually re-run the job worked. I wonder if connection pooling test is having some race to be failing. Anyways, let's merge this.

**Pull request merged**
